#!/usr/bin/env bash
set -euo pipefail
set -x

# トラッキングブランチが存在している場合のみ上書き防止のためにpullを行います。
if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' &>/dev/null; then
  git pull
fi

nix run . -- build
nix run . -- deploy
