name: www-ncaq-net
version: 0.1.1.0
synopsis: www.ncaq.net from Hakyll project template from stack
github: ncaq/www.ncaq.net
category: Web
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

language: GHC2021

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

other-extensions:
  - TemplateHaskell

dependencies:
  - base
  - convertible
  - directory
  - filepath
  - hakyll >=4.12.5.2
  - pandoc
  - regex-tdfa
  - split
  - text

executables:
  www-ncaq-net:
    main: site.hs
    ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wredundant-constraints
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
