name: www-ncaq-net
version: 0.1.1.0
synopsis: static site generate for www.ncaq.net by Hakyll
github: ncaq/www.ncaq.net
category: Web
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

language: GHC2021

default-extensions:
  - DataKinds
  - DefaultSignatures
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoImportQualifiedPost
  - OverloadedStrings
  - PartialTypeSignatures
  - RecordWildCards
  - TypeFamilies
  - ViewPatterns

other-extensions:
  - TemplateHaskell

dependencies:
  - base
  - convertible
  - directory
  - filepath
  - hakyll >=4.12.5.2
  - pandoc
  - regex-tdfa
  - split
  - text

executables:
  www-ncaq-net:
    main: site.hs
    ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
